### ISSUE TITLE
Create Hibernate Mapping File

### ISSUE THREAD

**Issue by akmad** [banda-health/openmrs-module-openhmis.plm#1]
While the SQL scripts to create the required database tables have been created, the hibernate mapping file to map between the DB and objects has not yet been created.

**Comment by danielshorten** [comment]
Where should the mapping files go?

According to http://docs.jboss.org/hibernate/orm/3.3/reference/en/html/session-configuration.html#configuration-programmatic Hibernate will look in the same package as the class file for an XML mapping file, but maybe we don't want XML in a Java package.

However, you can specify the location of mapping files in the Hibernate configuration file, so we can put them wherever we want.  Maybe a hibernate package under resources?

**Comment by danielshorten** [comment]
Sorry, I see that OpenMRS has a convention for this.  Never mind :)

**Comment by akmad** [comment]
Cool.  They usually go in the omod resources folder, right?

On Thu, Jul 19, 2012 at 9:49 AM, danielshorten <
reply@reply.github.com

**Comment by danielshorten** [comment]
Added in 4194720799b7d1b5045d7206ec96472e3ffdf8b9.
