### ISSUE TITLE
Fix Liquibase Script

### ISSUE THREAD

**Issue by akmad** [banda-health/openmrs-module-openhmis.plm#14]
Previously had errors with creating the FK's, now it appears to be trying to create tables that already exist.

Current Error Information:

ModuleFactory.startModuleInternal(603) |2012-07-17 14:22:16,491| Error while trying to start module: openhmis-plm
org.openmrs.module.ModuleException: Unable to update data model using liquibase.xml. Module: OpenHMIS Persistent List Manager Module
        at org.openmrs.module.ModuleFactory.runLiquibase(ModuleFactory.java:774)
        at org.openmrs.module.ModuleFactory.startModuleInternal(ModuleFactory.java:547)
        at org.openmrs.api.context.Daemon$1.run(Daemon.java:57)
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set liquibase.xml::openhmis.plm-2012-07-05-15:03::ibewes:
     Reason: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE `plm_list` (`id` INT AUTO_INCREMENT NOT NULL, `key` VARCHAR(250) NOT NULL, `list_provider` VARCHAR(500) NOT NULL, `description` VARCHAR(500) NULL, `date_created` DATETIME NOT NULL, CONSTRAINT `PK_PLM_LIST` PRIMARY KEY (`id`), UNIQUE (`key`)): Table 'plm_list' already exists:
          Caused By: Error executing SQL CREATE TABLE `plm_list` (`id` INT AUTO_INCREMENT NOT NULL, `key` VARCHAR(250) NOT NULL, `list_provider` VARCHAR(500) NOT NULL, `description` VARCHAR(500) NULL, `date_created` DATETIME NOT NULL, CONSTRAINT `PK_PLM_LIST` PRIMARY KEY (`id`), UNIQUE (`key`)): Table 'plm_list' already exists:
          Caused By: Table 'plm_list' already exists

**Comment by danielshorten** [comment]
I think the references in the foreign key constraints were reversed, so I fixed that.  The whole update runs with those changes.

commit 29b32b492f7a78a8c5bfc62932d4900476511b1c

Sorry for the superfluously added space.

**Comment by akmad** [comment]
Awesome... thanks for looking into it!
