### ISSUE TITLE
Create DB provider tests

### ISSUE THREAD

**Issue by akmad** [banda-health/openmrs-module-openhmis.plm#3]
Need to determine how best to test types that rely on the database.  I don't think the DB calls should be mocked, but can we rely on a test DB or should the creation of it be part of the test.

**Comment by akmad** [comment]
OpenMRS has some recommendations that I've been trying to follow: https://wiki.openmrs.org/display/docs/Unit+Tests

That page also mentions a plugin for Eclipse and IntelliJ that help automate the test method generation.

**Comment by danielshorten** [comment]
Added initial DatabaseServiceProvider tests in 4194720799b7d1b5045d7206ec96472e3ffdf8b9.  Tests use an in-memory HSQL database loaded from an XML file.
